language: c
compiler:
  - gcc

before_script:
  #installing libsodium, needed for Core
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - cd libsodium
  - git checkout tags/1.0.0 > /dev/null
  - ./autogen.sh > /dev/null
  - ./configure > /dev/null
  - make check -j3 > /dev/null
  - sudo make install >/dev/null
  - cd ..
  #creating libraries links and updating cache
  - sudo ldconfig > /dev/null
  # and toxcore
  - git clone git://github.com/irungentoo/toxcore.git > /dev/null
  - cd toxcore
  - autoreconf -i
  - CFLAGS="-Ofast -Wall -Wextra" ./configure --enable-daemon --enable-ntox
  - make -j3
  - make check
  - sudo make install
  - cd ..
  - sudo apt-get install libjsoncpp-dev

script:
  - mkdir build
  - cd build
  - cmake ../
  - make

notification:
  email: false
