language: c
sudo: false
compiler:
  - gcc

addons:
  apt:
    packages:
    - libjsoncpp-dev
    - libcap-dev

before_script:
  #installing libsodium, needed for Core
  - ./scripts/libsodium.sh
  #creating libraries links and updating cache
  #- sudo ldconfig > /dev/null
  # and toxcore
  - git clone git://github.com/irungentoo/toxcore.git > /dev/null
  - cd toxcore
  - autoreconf -i
  - CFLAGS="-Ofast -Wall -Wextra" ./configure --enable-daemon --enable-ntox --with-libsodium-headers=${HOME}/libsodium/ --with-libsodium-libs=${HOME}/libsodium/ --prefix=${HOME}/toxcore/
  - make -j3
  - make check
  - make install
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake ../ -DSTATIC=1
  - make

notification:
  email: false
